name: sample-app

services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-18080}:80'
            - '${VITE_PORT:-15173}:${VITE_PORT:-15173}'
        volumes:
            - '../../:/var/www/html'
        networks:
            - laravel
        depends_on:
            - mysql
            - redis
    microservice:
        build:
            context: .
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${MICROSERVICE_PORT:-18001}:80'
        volumes:
            - '../../microservice:/var/www/html'
        networks:
            - laravel
        depends_on:
            - mysql
            - redis
        command: ["php", "artisan", "queue:listen", "shared", "--queue=activity"]
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-13306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE:-sample}'
            MYSQL_USER: '${DB_USERNAME:-laravel}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'laravel-mysql:/var/lib/mysql'
            - './create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-password}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-16379}:6379'
        volumes:
            - 'laravel-redis:/data'
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
networks:
    laravel:
        driver: bridge
volumes:
    laravel-mysql:
        driver: local
    laravel-redis:
        driver: local
