[package]
name = "durable-workflow-polyglot-rust-worker"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
apache-avro = "=0.21.0"
base64 = "=0.22.1"
durable-workflow = "=2.0.0-rc.38"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "signal"] }

[dev-dependencies]
serde_json = "=1.0.150"
