#!/usr/bin/env bash
set -euo pipefail

# Polyglot end-to-end smoke. Runs every required polyglot scenario,
# asserts runnable surfaces, and emits machine-readable conformance
# metadata. A non-zero exit means a required published-artifact surface
# failed.

scripts_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

: "${DURABLE_WORKFLOW_SERVER_URL:?DURABLE_WORKFLOW_SERVER_URL must be set}"
: "${DURABLE_WORKFLOW_AUTH_TOKEN:=test-token}"
: "${DURABLE_WORKFLOW_NAMESPACE:=default}"
: "${DURABLE_SERVER_IMAGE:=durableworkflow/server:0.2.203}"
: "${DURABLE_WORKFLOW_CLI_VERSION:=0.1.70}"
: "${DURABLE_WORKFLOW_CLI_PIN:=dw==${DURABLE_WORKFLOW_CLI_VERSION}}"
: "${DURABLE_WORKFLOW_PYTHON_SDK_VERSION:=0.4.83}"
: "${DURABLE_WORKFLOW_PHP_SDK_PIN:=}"
: "${DURABLE_WORKFLOW_WATERLINE_PIN:=}"
: "${DURABLE_WORKFLOW_PHP_SDK_VERSION:=2.0.0-alpha.186}"
: "${DURABLE_WORKFLOW_WATERLINE_VERSION:=2.0.0-alpha.69}"
if [ -n "${DURABLE_WORKFLOW_PHP_SDK_PIN:-}" ]; then
    DURABLE_WORKFLOW_PHP_SDK_VERSION="${DURABLE_WORKFLOW_PHP_SDK_PIN#durable-workflow/workflow:}"
    DURABLE_WORKFLOW_PHP_SDK_VERSION="${DURABLE_WORKFLOW_PHP_SDK_VERSION%@*}"
fi
if [ -n "${DURABLE_WORKFLOW_WATERLINE_PIN:-}" ]; then
    DURABLE_WORKFLOW_WATERLINE_VERSION="${DURABLE_WORKFLOW_WATERLINE_PIN#durable-workflow/waterline:}"
    DURABLE_WORKFLOW_WATERLINE_VERSION="${DURABLE_WORKFLOW_WATERLINE_VERSION%@*}"
fi
if [ -z "${DURABLE_WORKFLOW_PHP_SDK_PIN:-}" ] && [ -n "${DURABLE_WORKFLOW_PHP_SDK_VERSION:-}" ]; then
    DURABLE_WORKFLOW_PHP_SDK_PIN="durable-workflow/workflow:${DURABLE_WORKFLOW_PHP_SDK_VERSION}"
fi
if [ -z "${DURABLE_WORKFLOW_WATERLINE_PIN:-}" ] && [ -n "${DURABLE_WORKFLOW_WATERLINE_VERSION:-}" ]; then
    DURABLE_WORKFLOW_WATERLINE_PIN="durable-workflow/waterline:${DURABLE_WORKFLOW_WATERLINE_VERSION}"
fi
: "${DURABLE_WORKFLOW_WATERLINE_URL:=http://waterline:8081/waterline}"
: "${DURABLE_WORKFLOW_ARTIFACT_PROBE_URL:=http://waterline:8081/polyglot/conformance/artifacts}"
export DURABLE_WORKFLOW_SERVER_URL DURABLE_WORKFLOW_AUTH_TOKEN DURABLE_WORKFLOW_NAMESPACE
export DURABLE_SERVER_IMAGE DURABLE_WORKFLOW_CLI_VERSION DURABLE_WORKFLOW_CLI_PIN DURABLE_WORKFLOW_PYTHON_SDK_VERSION
export DURABLE_WORKFLOW_PHP_SDK_PIN DURABLE_WORKFLOW_WATERLINE_PIN DURABLE_WORKFLOW_WATERLINE_URL
export DURABLE_WORKFLOW_PHP_SDK_VERSION DURABLE_WORKFLOW_WATERLINE_VERSION DURABLE_WORKFLOW_ARTIFACT_PROBE_URL

printf '\n==> polyglot smoke: server image %s\n' "$DURABLE_SERVER_IMAGE"
printf '==> polyglot smoke: dw CLI %s\n' "$DURABLE_WORKFLOW_CLI_PIN"
printf '==> polyglot smoke: artifact probe %s\n' "$DURABLE_WORKFLOW_ARTIFACT_PROBE_URL"
python "$scripts_dir/polyglot_smoke.py"
